#### **Import Libraries & Configure Display**

In [1]:
import pandas as pd
import numpy as np
import os

# Configure display options to see all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("Libraries loaded successfully!")

Libraries loaded successfully!

#### **Define File Paths & Load Datasets**

In [2]:
RAW_DIR = "../data/raw"

ember_path = os.path.join(RAW_DIR, "ember_yearly_generation.csv")
wb_path = os.path.join(RAW_DIR, "world_bank_electricity_access.csv")
irena_path = os.path.join(RAW_DIR, "irenastat_capacity.csv")

# Load datasets
df_ember = pd.read_csv(ember_path, low_memory=False)
df_wb = pd.read_csv(wb_path, low_memory=False)
df_irena = pd.read_csv(irena_path, low_memory=False)

print("Datasets loaded successfully into memory.")

Datasets loaded successfully into memory.

#### **Inspect Shape & First Few Rows of Ember Data**

In [3]:
print(f"Ember Shape: {df_ember.shape}")
df_ember.head(3)

Ember Shape: (104203, 24)

,Area,ISO 3 code,Year,Area type,Electricity source,Is aggregated source,Generation (TWh),Generation YoY change (TWh),Generation YoY change (%),Share of generation (%),Share of generation YoY change (% points),Capacity (GW),Emissions (MtCO2e),Emissions YoY change (MtCO2e),Emissions YoY change (%),Share of emissions (%),Emissions intensity (gCO2e/kWh),Continent,Ember region,EU member,OECD member,G20 member,G7 member,ASEAN member
0,ASEAN,NaN,2000,Region,Solar,False,0.07,NaN,NaN,0.016,NaN,0.00,0.003,NaN,NaN,0.001,42.857,NaN,NaN,False,False,False,False,False
1,ASEAN,NaN,2000,Region,Wind,False,0.00,NaN,NaN,0.000,NaN,0.00,0.000,NaN,NaN,0.000,NaN,NaN,NaN,False,False,False,False,False
2,ASEAN,NaN,2000,Region,Hydro,False,53.33,NaN,NaN,12.540,NaN,15.22,1.267,NaN,NaN,0.506,23.758,NaN,NaN,False,False,False,False,False

#### **Inspect Ember Data Types & Missing Values**

In [4]:
print("--- EMBER INFO ---")
print(df_ember.info())

print("\n--- EMBER MISSING VALUES (%) ---")
missing_ember = (df_ember.isnull().mean() * 100).round(2)
print(missing_ember[missing_ember > 0])

--- EMBER INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104203 entries, 0 to 104202
Data columns (total 24 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Area                                       104203 non-null  object
 1   ISO 3 code                                 97937 non-null   object
 2   Year                                       104203 non-null  int64
 3   Area type                                  104203 non-null  object
 4   Electricity source                         104203 non-null  object
 5   Is aggregated source                       104203 non-null  bool
 6   Generation (TWh)                           104203 non-null  float64
 7   Generation YoY change (TWh)                100459 non-null  float64
 8   Generation YoY change (%)                  67000 non-null   float64
 9   Share of generation (%)                    104169 non-null  float64
 10  Share of generation YoY change (% points)  100425 non-null  float64
 11  Capacity (GW)                              75897 non-null   float64
 12  Emissions (MtCO2e)                         97898 non-null   float64
 13  Emissions YoY change (MtCO2e)              94378 non-null   float64
 14  Emissions YoY change (%)                   55442 non-null   float64
 15  Share of emissions (%)                     97866 non-null   float64
 16  Emissions intensity (gCO2e/kWh)            63453 non-null   float64
 17  Continent                                  97937 non-null   object
 18  Ember region                               97937 non-null   object
 19  EU member                                  104203 non-null  bool
 20  OECD member                                104203 non-null  bool
 21  G20 member                                 104203 non-null  bool
 22  G7 member                                  104203 non-null  bool
 23  ASEAN member                               104203 non-null  bool
dtypes: bool(6), float64(11), int64(1), object(6)
memory usage: 14.9+ MB
None

--- EMBER MISSING VALUES (%) ---
ISO 3 code                                    6.01
Generation YoY change (TWh)                   3.59
Generation YoY change (%)                    35.70
Share of generation (%)                       0.03
Share of generation YoY change (% points)     3.63
Capacity (GW)                                27.16
Emissions (MtCO2e)                            6.05
Emissions YoY change (MtCO2e)                 9.43
Emissions YoY change (%)                     46.79
Share of emissions (%)                        6.08
Emissions intensity (gCO2e/kWh)              39.11
Continent                                     6.01
Ember region                                  6.01
dtype: float64

#### **Inspect World Bank Electricity Access Data**

In [5]:
print(f"World Bank Shape: {df_wb.shape}")
df_wb.head(3)

World Bank Shape: (265, 39)

,Country Name,Country Code,Indicator Name,Indicator Code,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,100.0,99.153656,99.197128,99.239914,100.0,100.0,100.0,100.0,100.0,100.0,91.700000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,93.400000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,99.900000,100.000000,100.000000
1,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.917256,19.944277,21.548647,22.493217,23.724455,23.449539,25.172482,26.795145,25.908845,26.187846,27.414954,28.909756,31.673427,31.723574,31.871956,33.922276,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.742043,50.667516,52.598171
2,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.400000,9.300000,14.100000,19.000000,23.800000,28.700000,33.500000,38.400000,42.400000,48.300000,42.700000,43.200000,69.100000,68.000000,89.500000,71.500000,97.700000,97.700000,93.400000,97.700000,97.700000,97.700000,85.300000,85.300000,87.800000

#### **Inspect IRENASTAT Capacity Data**

In [6]:
print(f"IRENA Shape: {df_irena.shape}")
print(df_irena.info())
df_irena.head(3)

IRENA Shape: (288, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288 entries, 0 to 287
Data columns (total 5 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Region                             288 non-null    object
 1   Technology                         288 non-null    object
 2   Data Type                          288 non-null    object
 3   Year                               288 non-null    int64
 4   Electricity generation statistics  288 non-null    object
dtypes: int64(1), object(4)
memory usage: 11.4+ KB
None

,Region,Technology,Data Type,Year,Electricity generation statistics
0,Africa,Total renewable,Electricity Generation (GWh),2000,78948.79
1,Africa,Total renewable,Electricity Generation (GWh),2001,85987.3
2,Africa,Total renewable,Electricity Generation (GWh),2002,84118.8

#### **Check Unique Countries & Coverage in Ember**

In [7]:
# Check unique countries in Ember dataset
if 'Area' in df_ember.columns:
    print(f"Total unique regions in Ember: {df_ember['Area'].nunique()}")
    print(df_ember['Area'].unique()[:15]) # Previewing first 15
elif 'Country' in df_ember.columns:
    print(f"Total unique regions in Ember: {df_ember['Country'].nunique()}")
    print(df_ember['Country'].unique()[:15])

Total unique regions in Ember: 224
['ASEAN' 'AU' 'Afghanistan' 'Africa' 'Albania' 'Algeria' 'American Samoa'
 'Angola' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba' 'Asia'
 'Australia' 'Austria']